spring.application.name=todolist
##=============================================================
## propriedades do banco de dados MariaDB
##=============================================================
spring.datasource.url=jdbc:mariadb://localhost:3306/todolist
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## O comando abaixo garante que o Hibernate saiba exatamente como gerar SQL para o MariaDB.
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


##=============================================================
##  O comando spring.jpa.hibernate.ddl-auto=update serve para que o Hibernate \
##  atualize automaticamente o esquema do banco de dados (tabelas, colunas, �ndices) \
##  com base nas entidades Java (@Entity) mapeadas, sem apagar os dados existentes. \
##  Ele cria tabelas ausentes e adiciona novas colunas, sendo ideal para fases de desenvolvimento.
##=============================================================
spring.jpa.hibernate.ddl-auto=update

## Ativando o log do hibernate pra tentar entende porque n�o est� criando a tabela:
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE